/**
 * @file    ky040.h
 * @brief   Component driver for KY-040 rotary encoder module.
 * @details Uses BSP TIM3 hardware encoder interface and GPIO button input
 *          to compute physical detents, debounce mechanical contacts, differentiate
 *          between short clicks and long holds, and dispatch navigation events
 *          to a FreeRTOS queue.
 */

#ifndef KY040_H
#define KY040_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "tim.h"
#include "gpio.h"

#include "FreeRTOS.h"
#include "queue.h"
#include "task.h"


/**
 * @brief Status codes for KY-040 component driver.
 */
typedef enum {
    KY040_OK       = 0,  /**< Operation successful */
    KY040_ERR_INIT = 1   /**< Queue or hardware initialization failure */
} KY040_Status_t;

/**
 * @brief User interface navigation events generated by KY-040 encoder.
 */
typedef enum {
    KY040_EVENT_NONE = 0,   /**< No pending event */
    KY040_EVENT_CW,         /**< Clockwise rotation (turn right / scroll down) */
    KY040_EVENT_CCW,        /**< Counter-clockwise rotation (turn left / scroll up) */
    KY040_EVENT_CLICK,      /**< Short button click (< 600 ms, Enter / Select) */
    KY040_EVENT_HOLD        /**< Long button hold (>= 600 ms, Back / Return) */
} KY040_Event_t;

/**
 * @brief  Initializes the KY-040 component, invoking low-level timer/GPIO setup
 *         and creating the FreeRTOS event queue.
 * @param  None.
 * @return KY040_OK on success, KY040_ERR_INIT on failure.
 */
KY040_Status_t KY040_Init(void);

/**
 * @brief  Scans encoder counter and push-button state, applies debouncing,
 *         and enqueues detected rotation and click events.
 * @note   Must be called periodically (e.g., every 5 to 10 ms).
 * @param  None.
 * @return None.
 */
void KY040_Update(void);

/**
 * @brief  Retrieves the next navigation event from the KY-040 event queue.
 * @param[out] event       Pointer to store the received event.
 * @param[in]  timeout_ms  Maximum duration in ms to block waiting for an event.
 * @return true if an event was dequeued, false on timeout or error.
 */
bool KY040_GetEvent(KY040_Event_t *event, uint32_t timeout_ms);

/**
 * @brief  Retrieves the raw signed counter delta since last query.
 * @param  None.
 * @return Signed number of counter steps.
 */
int16_t KY040_GetRawDelta(void);


#endif /* KY040_H */
